// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVerseFunction.Models;

public partial class Course
{
    public int CourseId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public string CourseType { get; set; }

    public int? SeatsAvailable { get; set; }

    public decimal Duration { get; set; }

    public int CategoryId { get; set; }

    public int InstructorId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string? Thumbnail { get; set; }

    public virtual CourseCategory Category { get; set; }

    public virtual ICollection<Enrollment> Enrollments { get; set; } = new List<Enrollment>();

    public virtual Instructor Instructor { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<SessionDetail> SessionDetails { get; set; } = new List<SessionDetail>();
}