// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVerseFunction.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int CourseId { get; set; }

    public int UserId { get; set; }

    public int Rating { get; set; }

    public string Comments { get; set; }

    public DateTime ReviewDate { get; set; }

    public virtual Course Course { get; set; }

    public virtual UserProfile User { get; set; }
}