// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVerseFunction.Models;

public partial class SessionDetail
{
    public int SessionId { get; set; }

    public int CourseId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string VideoUrl { get; set; }

    public int VideoOrder { get; set; }

    public virtual Course Course { get; set; }
}